Provisioning.Agent=auto
Provisioning.Enabled=n
Provisioning.UseCloudInit=y
Provisioning.AllowResetSysUser=n
Provisioning.RegenerateSshHostKeyPair=n
Provisioning.DeleteRootPassword=n
Provisioning.DecodeCustomData=n
Provisioning.ExecuteCustomData=n
Provisioning.MonitorHostName=n
ResourceDisk.Format=n
ResourceDisk.EnableSwap=n
ResourceDisk.MountPoint=/mnt/resource
ResourceDisk.MountOptions=None
ResourceDisk.Filesystem=ext4
ResourceDisk.EnableSwapEncryption=n
Extensions.Enabled=y
AutoUpdate.Enabled=y
Logs.Verbose=n
OS.AllowHTTP=n
OS.CheckRdmaDriver=n
